-- This config was built follow chris@machine's neovim from scratch series
-- The .lua extensions are inferred by lua. In lsp's case, lua searches for init.lua

require("shahbaz.alpha")
require("shahbaz.autopairs")
require("shahbaz.bufferline")
require("shahbaz.cmp")
require("shahbaz.colorscheme")
require("shahbaz.comment")
require("shahbaz.gitsigns")
require("shahbaz.indent-blankline")
require("shahbaz.keymaps")
require("shahbaz.lualine")
require("shahbaz.lsp")
require("shahbaz.nvim-tree")
require("shahbaz.options")
require("shahbaz.plugins")
require("shahbaz.telescope")
require("shahbaz.toggleterm")
require("shahbaz.treesitter")
require("shahbaz.whichkey")
require("shahbaz.catppuccin")
require("shahbaz.todo-comments")
